### PR TITLE
feat: support optional property workspace.solution.defaultRunTemplateDataset

### PR DESCRIPTION
**Pull request by csm-thu**
The scenario creation dialog will use this optional property if it exists to automatically select a default dataset when switching between run types

### CODE REVIEW

**Review by esasova — APPROVED** [review]
LGTM :+1:

**Review by nborde-CSM — APPROVED** [review]
LGTM :+1:

**Review by esasova — APPROVED** [review]
LGTM :+1:

**Review by nborde-CSM — APPROVED** [review]
LGTM :+1:

**Pull request merged**
